instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls',namespace="post_app")),
    path('profile/',include('profiles.urls',namespace="profiles")),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('oauth/', include('social_django.urls', namespace='social')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views


app_name="post_app"


urlpatterns = [
    path('newsfeed/',views.index,name="index"),
    path('',views.main,name="main"),


    # path('post/<int:pk>',views.index,name="index"),


    path('edit/<int:pk>',views.update,name="update"),
    path('delete/<int:pk>',views.delete,name="delete"),
    path('<int:pk>/',views.details,name="details"),
    path('like/',views.like,name="post-like"),
    path('posts/',views.all_post,name="allposts"),


    

]

profiles/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views


app_name="profilies"


urlpatterns = [  
    # path('profile/',views.profile,name="profile-form"),
    path('profile-edit/',views.profile_update,name="profile-update"),
    path('<str:username>/follow/',views.Userfollow,name="follow"),
    path('',views.search,name="search"),
    path('<str:author>/',views.profile,name="profile"),
    path('<str:author>/photos',views.profile_p,name="photos"),
    path('<str:author>/about',views.profile_a,name="about"),
    path('user/followers/',views.follow_list,name="followers"),

]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
# Create your models here.

class Profile(models.Model):
	user=models.OneToOneField(User,on_delete=models.CASCADE)
	profile_img=models.ImageField(null=True,blank=True,default="default.png")
	cover_img=models.ImageField(null=True,blank=True,)
	location=models.CharField(null=True,blank=True,max_length=100)
	education=models.CharField(null=True,blank=True,max_length=100)
	work_at=models.CharField(null=True,blank=True,max_length=100)
	bio=models.CharField(null=True,blank=True,max_length=50)
	following=models.ManyToManyField(User,blank=True,related_name='followed_by')


	def __str__(self):
		return self.user.username

	def get_following(self):
		users=self.following.all()
		return users.exclude(username=self.user.username)

	def get_absolute_url(self):
		return reverse('profilies:profile',args=[self.user.username])	

def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile=Profile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile,sender=User)

profiles/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=('profile_img','cover_img','location','education','work_at','bio')

profiles/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import ProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import Http404,HttpResponseRedirect,JsonResponse
from post.models import Post
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
# def profile(request):
# 	if request.method=="POST":
# 		form=ProfileForm(request.POST or None,request.FILES)
# 		if form.is_valid():
# 			f=form.save(commit=False)
# 			f.user=request.user
# 			f.save()
# 			return redirect('post_app:index')
# 	else:
# 		form=ProfileForm()
# 	context={'form':form,}
# 	return render(request,'profiles/profileform.html',context)

@login_required()
def profile_update(request):
	if request.method=="POST":
		form=ProfileForm(request.POST or None,request.FILES,instance=request.user.profile)
		if form.is_valid():
			f=form.save(commit=False)
			f.user=request.user
			f.save()
			return redirect('post_app:index')
	else:
		form=ProfileForm(instance=request.user.profile)
	context={'form':form,}
	return render(request,'profiles/profile-update.html',context)	


def Userfollow(request,username,*args,**kwargs):
	is_follow=False
	user_f=get_object_or_404(User,username=username)
	user_add=request.user
	if user_f in user_add.profile.following.all():
		user_add.profile.following.remove(user_f)
		is_follow=False
	else:
		user_add.profile.following.add(user_f)
		is_follow=True
	return redirect(user_f.profile.get_absolute_url())		


@login_required()
def search(request):
			# qs=User.objects.all()
			qs=Post.objects.all()
			qs_u=User.objects.all()
			query=request.GET.get('q')
			if query:
				# qs=qs.filter(Q(username__icontains=query)					
				# 	)
				qs=qs.filter(Q(content__icontains=query)|
					Q(author__username__icontains=query)
					)
				qs_u=qs_u.filter(
					Q(username__icontains=query)
					)	
			return render(request,"profiles/search.html",{'posts':qs,'qs_u':qs_u})

login_required()
def profile(request,author,**kwargs):
	user=get_object_or_404(User,username=author)
	post=Post.objects.filter(author=user).order_by('-creat_at')
	post_c=Post.objects.filter(author=user).count()
	user_p=User.objects.get(username=user)
	if user_p in request.user.profile.following.all():
		is_follow=True
	else:
		is_follow=False
	active_p=True

	context={'post':post,'user_p':user_p,'is_follow':is_follow,'active_p':active_p,'post_c':post_c}
	return render(request,'profiles/profile.html',context)

login_required()
def profile_p(request,author,**kwargs):
	user=get_object_or_404(User,username=author)
	post=Post.objects.filter(author=user).order_by('-creat_at')
	active_pp=True
	user_p=User.objects.get(username=user)
	context={'post':post,'user_p':user_p,'active_pp':active_pp,}
	return render(request,'profiles/photo.html',context)

login_required()
def profile_a(request,author,**kwargs):
	user=get_object_or_404(User,username=author)
	post=Post.objects.filter(author=user).order_by('-creat_at')
	user_p=User.objects.get(username=user)
	active_a=True
	context={'post':post,'user_p':user_p,'active_a':active_a}
	return render(request,'profiles/about.html',context)

def follow_list(request):
	user=request.user
	context={
		'user':user
	}
	return render(request,'profiles/follow_info.html',context)

profiles/templates/profiles/about.html
{% extends 'base.html' %}



{% block content %}

<section id='profile'>
    
{% if user_p.profile.cover_img %}
        <div class="cover">
            <img src="{{user_p.profile.cover_img.url}}">
        </div>
        {% else %}
        <div class="cover">
               <h1>No Cover Photo Avalable.</h1>
        </div>
{% endif %}
<div class="profile-pic">
    <img src="{{user_p.profile.profile_img.url}}">
    <h3 style="text-align:center"><strong style="text-align:center">{{user_p.username|capfirst}}</strong></h3>
</div>
<div class="follow">
    {% if is_follow == True %}<a href="{% url 'profilies:follow' user_p.username %}" id="follow-btn">unfollow</a>{% endif %}
    {% if is_follow == False %} <a href="{% url 'profilies:follow' user_p.username %}" id="follow-btn">follow</a>{% endif %}
    
      
    <strong>followers <small>({{user_p.followed_by.count}})</small></strong>
    
    </div>
<div class="nav">
  <ul>    
  <li><a href="{% url 'profilies:profile' user_p.profile.user.username %}">Timeline</a></li>
     
      <li><a href="{% url 'profilies:photos' user_p.profile.user.username %}">Photos</a></li>
  
  <li><a href="{% url 'profilies:about' user_p.profile.user.username %}" {% if active_a %} class="blue" {% endif %}>about</a></li>
  </ul>    
  
  </div>


<div class="about">
    <ul>
        <li>
            <h3><strong>Name : </strong> <small>{{ user_p.profile.user.username }}</small></h3>
        </li>
        <li>
                <h3><strong>First Name : </strong> <small>{{ user_p.profile.user.first_name }}</small></h3>
        </li>
        <li>
                <h3><strong>Last Name : </strong> <small>{{ user_p.profile.user.last_name }}</small></h3>
        </li>
        <li>
            <h3><strong>Email : </strong> <small>{{ user_p.profile.user.email }}</small></h3>
        </li>
        <li>
                <h3><strong>Bio : </strong> <small>{{ user_p.profile.bio }}</small></h3>
        </li>
        <li>
                <h3><strong>Study : </strong> <small>{{ user_p.profile.education }}</small></h3>
        </li>
        <li>
                <h3><strong>Working At : </strong> <small>{{ user_p.profile.work_at }}</small></h3>
        </li>
        <li>
                <h3><strong>Live In : </strong> <small>{{ user_p.profile.location }}</small></h3>
        </li>
       

    </ul>

</div>




</section>






    
{% endblock %}

profiles/templates/profiles/follow_info.html
{% extends 'base.html' %}
{% block content %}
<section class="search">
    <div class="follow-info">
        <div class="following">
            <h1>Following</h1>
            {% for user in user.profile.following.all %}
                     <img src="{{user.profile.profile_img.url}}">
                
                <a href="{% url 'profilies:profile' user.username %}">{{user.username}}</a>
                <strong>Folowers <small>({{user.followed_by.count}})</small></strong>

            {% empty %}
                <h1 style="text-align: center">You are Not Following anyone.</h1>
            {% endfor %}
        </div>


        <div class="followed-by">
                <h1>Followers</h1>
            {% for profile in user.followed_by.all %}
                
                <img src="{{profile.user.profile.profile_img.url}}">
                <span><b>{{profile.user.username}}</b></span><br>
                <strong>Folowers <small>({{profile.user.followed_by.count}})</small></strong>
                <a href="{% url 'profilies:profile' profile.user.username %}">View</a>
            
            {% empty %}
                <h1 style="text-align: center">You are Not Followed By anyone.</h1>
            {% endfor %}
        </div>
        </div>
    </section>        
{% endblock %}

profiles/templates/profiles/photo.html
{% extends 'base.html' %}



{% block content %}

<section id='profile'>
{% if user_p.profile.cover_img %}
<div class="cover">
    <img src="{{user_p.profile.cover_img.url}}">
</div>
{% else %}
<div class="cover">
       <h1>No Cover Photo Avalable.</h1>
</div>
{% endif %}    
<div class="profile-pic">
    <img src="{{user_p.profile.profile_img.url}}">
    <h3 style="text-align:center"><strong style="text-align:center">{{user_p.username|capfirst}}</strong></h3>
</div>
<div class="follow">
    {% if is_follow == True %}<a href="{% url 'profilies:follow' user_p.username %}" id="follow-btn">unfollow</a>{% endif %}
    {% if is_follow == False %} <a href="{% url 'profilies:follow' user_p.username %}" id="follow-btn">follow</a>{% endif %}
    
      
    <strong>followers <small>({{user_p.followed_by.count}})</small></strong>
    
    </div>
<div class="nav">
  <ul>    
  <li><a href="{% url 'profilies:profile' user_p.profile.user.username %}">Timeline</a></li>
     
      <li><a href="{% url 'profilies:photos' user_p.profile.user.username %}" {% if active_pp %} class="blue" {% endif %}>Photos</a></li>
  
  <li><a href="{% url 'profilies:about' user_p.profile.user.username %}">about</a></li>
  </ul>    
  
  </div>

  <h5 style="text-align: center;">Photos </h5>
  <div class="post">
       {% for post in post%}
           {% if post.img %}<div class="post-img"><img src="{{post.img.url}}"></div>{% endif %}
       
       {% empty %}
           <h5 style="text-align: center;">No Photos avalaible</h5>
       {% endfor %}
     </div>

</section>




<!-- {% if user_p.profile.profile_img %}
<img src="{{user_p.profile.profile_img.url}}">
{% endif %} -->


    
{% endblock %}

profiles/templates/profiles/profile-update.html
{% extends 'base.html' %}
{% block content %}
<div class="profile-form">
		
<form method="post" enctype="multipart/form-data" class="p-form">
	<h3 class="formheading">Change Profile Info.</h3>
	{% csrf_token %}

	{{form.as_p}}
	<button type="submit">Save</button>
</form>
</div>
{% endblock %}

profiles/templates/profiles/profile.html
{% extends 'base.html' %}



{% block content %}

<section id='profile'>
    
{% if user_p.profile.cover_img %}
    <div class="cover">
        <img src="{{user_p.profile.cover_img.url}}">
    </div>
    {% else %}
    <div class="cover">
           <h1>No Cover Photo Avalable.</h1>
    </div>
{% endif %}
<div class="profile-pic">
    <img src="{{user_p.profile.profile_img.url}}">
    <h3 style="text-align:center"><strong style="text-align:center">{{user_p.username|capfirst}}</strong></h3>
</div>
<div class="follow">
    {% if is_follow == True %}<a href="{% url 'profilies:follow' user_p.username %}" id="follow-btn">unfollow</a>{% endif %}
    {% if is_follow == False %} <a href="{% url 'profilies:follow' user_p.username %}" id="follow-btn">follow</a>{% endif %}
    
      
    <strong>followers <small>({{user_p.followed_by.count}})</small></strong>
    
    </div>
<div class="nav">
  <ul>    
  <li><a href="{% url 'profilies:profile' user_p.profile.user.username %}" {% if active_p %} class="blue" {% endif %}>Timeline</a></li>
     
      <li><a href="{% url 'profilies:photos' user_p.profile.user.username %}">Photos</a></li>
  
  <li><a href="{% url 'profilies:about' user_p.profile.user.username %}">about</a></li>
  </ul>    
  
</div>







<!-- {% if user_p.profile.profile_img %}
<img src="{{user_p.profile.profile_img.url}}">
{% endif %} -->
<h5 style="text-align: center;">Posts ({{ post_c }})</h5>
   <div class="post">
        {% for post in post%}
        <div class="inner-post">
          <div class="profile-img"><img src="{{post.author.profile.profile_img.url}}">
            <a href="{% url 'profilies:profile' post.author.username %}">{{post.author.username}} </a> <span> |   {{post.creat_at|timesince}} ago</span>
            
          </div>
          {% if post.author == request.user %}
          <div class="icone_post"><i class="fas fa-ellipsis-v"></i> 
          </div>
          
          <div class="post_menu">
            <ul>
              <li  id="border"><a href="{% url 'post_app:update' post.pk %}">Edit Post</a></li>
              <li><a href="{% url 'post_app:delete' post.pk %}">Delete Post</a></li>

            </ul>
          </div>
          {% endif %}
          <p>{{post.content}}</p>
          {% if post.img %}<div class="post-img"><img src="{{post.img.url}}"></div>{% endif %}
          
          <a href="{% url 'post_app:details' post.pk %}" id="link2">View Post</a>
        </div>
        {% empty %}
            <h5 style="text-align: center;">No post avalaible</h5>
        {% endfor %}
      </div>


</section>    
{% endblock %}

profiles/templates/profiles/search.html
{% extends 'base.html' %}


{% block content %}
<section class="search">
<h1 style='text-align:center'>Users</h1>
<div class="user-card">
        
        {% for user in qs_u %}
          <div class="inner-u-card">
              <img src="{{user.profile.profile_img.url}}">
              <span><b>{{user.username}}</b></span>
              <strong>Folowers <small>({{user.followed_by.count}})</small></strong><br><br>
              <a href="{% url 'profilies:profile' user.username %}">View</a>
          </div>
        {% endfor %}
</div>

<h1 style='text-align:center'>Posts</h1>
{% for post in posts %}
  
 
<div class="inner-post">
        <div class="profile-img"><img src="{{post.author.profile.profile_img.url}}">
          <a href="{% url 'profilies:profile' post.author.username %}">{{post.author.username}} </a> <span> |   {{post.creat_at|timesince}} ago</span>
          
        </div>
        {% if post.author == request.user %}
        <div class="icone_post"><i class="fas fa-ellipsis-v"></i> 
        </div>
        
        <div class="post_menu">
          <ul>
            <li  id="border"><a href="{% url 'post_app:update' post.pk %}">Edit Post</a></li>
            <li><a href="{% url 'post_app:delete' post.pk %}">Delete Post</a></li>

          </ul>
        </div>
        {% endif %}
        <p>{{post.content}}</p>
        {% if post.img %}<div class="post-img"><img src="{{post.img.url}}"></div>{% endif %}
        
        <a href="{% url 'post_app:details' post.pk %}" id="link2">View Post</a>
      </div>
    




{% endfor %} 
</section>
{% endblock %}