accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.contrib.auth import views as auth_views

app_name="accounts"


urlpatterns = [
    
    path('signup/',views.signup,name='signup'),
    path('account-settings/',views.account_settings,name='account-setting'),
    path('password/',views.passchange,name='passchange'),
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name="login"),
    path('logout/',auth_views.LogoutView.as_view(template_name='accounts/login.html'),name="logout"),

]

instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls',namespace="post_app")),
    path('profile/',include('profiles.urls',namespace="profiles")),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('oauth/', include('social_django.urls', namespace='social')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views


app_name="post_app"


urlpatterns = [
    path('newsfeed/',views.index,name="index"),
    path('',views.main,name="main"),


    # path('post/<int:pk>',views.index,name="index"),


    path('edit/<int:pk>',views.update,name="update"),
    path('delete/<int:pk>',views.delete,name="delete"),
    path('<int:pk>/',views.details,name="details"),
    path('like/',views.like,name="post-like"),
    path('posts/',views.all_post,name="allposts"),


    

]

profiles/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views


app_name="profilies"


urlpatterns = [  
    # path('profile/',views.profile,name="profile-form"),
    path('profile-edit/',views.profile_update,name="profile-update"),
    path('<str:username>/follow/',views.Userfollow,name="follow"),
    path('',views.search,name="search"),
    path('<str:author>/',views.profile,name="profile"),
    path('<str:author>/photos',views.profile_p,name="photos"),
    path('<str:author>/about',views.profile_a,name="about"),
    path('user/followers/',views.follow_list,name="followers"),

]

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


# Create your models here.
class Post(models.Model):
    content=models.TextField()
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    creat_at=models.DateTimeField(auto_now_add=True)
    like=models.ManyToManyField(User,related_name='likes',blank=True)
    view_count=models.IntegerField(default=0)
    img=models.ImageField(null=True,blank=True)


    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('post_app:details',args=[self.pk])

    def total_likes(self):
    	return self.like.count()

    def increase(self):
    	self.view_count+=1
    	self.save()

class Comments(models.Model):
	comment_content=models.TextField()
	c_by=models.ForeignKey(User,on_delete=models.CASCADE,related_name="c_ed")
	reply=models.ForeignKey("Comments",blank=True,null=True,related_name="replies",on_delete=models.CASCADE,)
	post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='blabla')
	created_on=models.DateTimeField(auto_now_add=True)
		
	def __str__(self):
		return self.post.content

post/forms.py
from django import forms
from .models import Post
from .models import Comments


class PostForm(forms.ModelForm):
	content=forms.CharField(label="",widget=forms.Textarea(attrs={'class':'post_form','rows':'5','cols':'50','placeholder':'Write Something....'}))
	class Meta:
 		model=Post
 		fields=('content','img')

    # def __init__(self, *args, **kwargs):
    #     super(PostForm, self).__init__(*args, **kwargs)
    #     self.fields['content'].widget.attrs['placeholder'] = 'Write Something'


class CommentForm(forms.ModelForm):
	comment_content=forms.CharField(label="Comment",widget=forms.Textarea(attrs={'class':'comment-form','rows':'1','cols':'40'}))
	class Meta:
 		model=Comments
 		fields=('comment_content',)       

post/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Post
from django.template.loader import render_to_string
from .forms import PostForm
from django.http import Http404,HttpResponseRedirect,JsonResponse
# from rest_framework.generics import ListAPIView
from django.views.decorators.csrf import csrf_exempt
from .models import Comments
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.contrib import messages
# Create your views here.
# @csrf_exempt
@login_required()
def like(request,*args,**kwargs):
    # post=get_object_or_404(Post,id=request.POST.get("post_id"))
    post=get_object_or_404(Post,id=request.POST.get('id'))

    is_like=False
    if post.like.filter(id=request.user.id).exists():
        post.like.remove(request.user)
        is_like=False
    else:
        post.like.add(request.user)    
        is_like=True
    context={'post':post,'is_like':is_like,'total_likes':post.total_likes()}    
    if request.is_ajax():
        html=render_to_string('post_app/like_section.html',context,request=request)
        return JsonResponse({'form':html})
    

@login_required()
def index(request):
    i_following=request.user.profile.get_following()
    post=Post.objects.filter(author__in = i_following)
    post_u=Post.objects.filter(author = request.user).count() 

    if request.method=="POST":
        form=PostForm(request.POST,request.FILES)
        if form.is_valid():
            s=form.save(commit=False)
            s.author=request.user
            s.save()
            messages.success(request,'Your Post Has Been Created.')
            return redirect('post_app:index')
    else:
        form=PostForm()
                          
    context={'post':post,'form':form,'post_u':post_u}
    return render(request,'post_app/index.html',context)


    

@login_required()
def details(request,pk):
    post=get_object_or_404(Post,pk=pk)
    if post:
        post.increase()
    is_like=False
    if post.like.filter(id=request.user.id).exists():
        is_like=True
    comments=Comments.objects.filter(post=post,reply=None).order_by('-created_on')
    if request.method=="POST":
        comment_form=CommentForm(request.POST or None)
        if comment_form.is_valid():
            comment_content=request.POST.get('comment_content')
            reply_id=request.POST.get('comment_id')
            comment_qs=None
            if reply_id:
                comment_qs=Comments.objects.get(id=reply_id)
            # post_d = get_object_or_404(Post,id=c_post)
            comment=Comments.objects.create(comment_content=comment_content,c_by=request.user,post=post,reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form=CommentForm()
    context={'post':post,'comments':comments,'comment_form':comment_form,'is_like':is_like,'total_likes':post.total_likes()}
    if request.is_ajax():
        html=render_to_string('post_app/comment_section.html',context,request=request)
        return JsonResponse({'form':html})
    return render(request,'post_app/details.html',context)

@login_required()
def update(request,pk):
    post=get_object_or_404(Post,pk=pk)
    if post.author==request.user:
        if request.method=="POST":
            form=PostForm(data=request.POST,instance=post)
            if form.is_valid():
                form.save()
                messages.success(request,'Your Post Updated Successfully.')
                return redirect('post_app:index')
        else:
            form=PostForm(instance=post)
    else:
        raise http404()
    context={'form':form}
    return render(request,'post_app/update.html',context)

@login_required()
def delete(request,pk):
    post=get_object_or_404(Post,pk=pk)
    if post.author==request.user:
        post.delete()
        messages.success(request,'Your Post Deleted Successfully.')
    else:
        raise http404()
    return redirect('post_app:index')

@login_required()
def all_post(request):
    post=Post.objects.all().order_by('-creat_at')
    if request.method=="POST":
        form=PostForm(request.POST or None,request.FILES)
        if form.is_valid():
            s=form.save(commit=False)
            s.author=request.user
            s.save()
            return redirect('post_app:allposts')
    else:
        form=PostForm()
    return render(request,'post_app/all.html',{'post':post,'form':form})


def main(request):
    main=True
    return render(request,'post_app/main.html',{'main':main})    

post/templates/post_app/all.html
{% extends 'base.html' %}



{% block content %}

    <div class="a_form">
        <form class="create-formm" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
      
            <button type="submit">Post</button>
      
          </form>
    </div>
</div> 
  <section class="front">
    <div class="inner-front">
      
      <div class="post">
        {% for post in post%}
        <div class="inner-post">
          <div class="profile-img"><img src="{{post.author.profile.profile_img.url}}">
            <a href="{% url 'profilies:profile' post.author.username %}">{{post.author.username}} </a> <span> |   {{post.creat_at|timesince}} ago</span>
            
          </div>
          {% if post.author == request.user %}
          <div class="icone_post"><i class="fas fa-ellipsis-v"></i> 
          </div>
          
          <div class="post_menu">
            <ul>
              <li  id="border"><a href="{% url 'post_app:update' post.pk %}">Edit Post</a></li>
              <li><a href="{% url 'post_app:delete' post.pk %}">Delete Post</a></li>

            </ul>
          </div>
          {% endif %}
          <p>{{post.content}}</p>
          {% if post.img %}<div class="post-img"><img src="{{post.img.url}}"></div>{% endif %}
          
          <a href="{% url 'post_app:details' post.pk %}" id="link2">View Post</a>
        </div>
        {% endfor %}
      </div>
      <!-- <div class="latest_post"></div> -->
    </div>
  




  </section>
{% endblock %}

post/templates/post_app/comment_section.html
<div class="d-comment">
    <h3>Add Comment Here......</h3>
     <form method="post" class="comment-formm" action=".">

          {% csrf_token %}
          {{comment_form}}
          <!-- <input type="hidden" name="comment_id" value="{{ comment.id }}"> -->

          <button type="submit">comment</button>
        </form>
        <h5>{{ comments.count }} Comment{{ comments|pluralize}}</h5>
  

  <div class='comment-r'>

     {% for comment in comments %}
     <div class="inner-c">
      <div class="profile-img"><img src="{{comment.c_by.profile.profile_img.url}}"><a href="{% url 'profilies:profile' comment.c_by.username %}">{{comment.c_by.username}} </a> <span> |   {{comment.created_on|timesince}} ago</span>
        </div>
        <p style="margin: 10px 0 10px 0px"><strong>{{comment.comment_content}}</strong><button id="style2">Reply</button></p>


     <!-- <div class="reply-s"> 
      <form method="post" class="reply-formm" action=".">
          <input type="hidden" name="comment_id" value="{{ comment.id }}">
           {% csrf_token%}
          {{ comment_form.as_p }}
         <button type="submit" id="style3">Submit</button>
      </form>
      {% for reply in comment.replies.all %}
           <div class="profile-img"><img src="{{reply.c_by.profile.profile_img.url}}"><a href="{% url 'profilies:profile' reply.c_by.username %}">{{reply.c_by.username}} </a> <span> |   {{reply.created_on|timesince}} ago</span>
          </div>
            <p style="margin: 10px 0 10px 0px"><strong>{{reply.comment_content}}</strong></p>

        {% endfor %}
     </div>    -->
    {% endfor %}

    </div>
    
  </div>
</div>

post/templates/post_app/details.html
{% extends 'base.html' %}

{% block content %}
    <section class="detail">
         <!--  {% for comment in comments %}
        <p>{{comment.comment_content}} | {{comment.c_by}}</p>
        
        <form method="post" style="width: 40%">
            <input type="hidden" name="comment_id" value="{{ comment.id }}">
             {% csrf_token%}
            {{ comment_form.as_p }}
           <button type="submit" class="btn btn-primary btn-sm">Reply</button><br><br>
        </form>
        {% for reply in comment.replies.all %}
            <p>{{ reply.comment_content }} | by{{ reply.c_by }}</p>
          {% endfor %}   
      {% endfor %} -->




<div class="post">
   
        <div class="inner-post">
          <div class="profile-img"><img src="{{post.author.profile.profile_img.url}}"><a href="{% url 'profilies:profile' post.author.username %}">{{post.author.username}} </a> <span> |   {{post.creat_at|timesince}} ago</span>
            
          </div>
         
          <p>{{post.content}}</p>
          {% if post.img %}<div class="post-img"><img src="{{post.img.url}}"></div>{% endif %}
          <div id="like">
           {% include 'post_app/like_section.html' %}
          </div>  
        </div>
        
      <!-- <div class="latest_post"></div> -->
      <div id="main-comment-section">
        {% include 'post_app/comment_section.html' %}
       </div>  
</div> 
</section>

{% endblock %}      

post/templates/post_app/index.html
{% extends 'base.html' %}



{% block content %}
<div class="m-grid">
  <div class="profile">
      <!-- <div class="inner-profile">
         {% if request.user.profile.cover_img %} <img src="{{request.user.profile.cover_img.url}}" id='cover-img'>
         
         {% endif %} 

        <img src="{{request.user.profile.profile_img.url}}" id="profile-img">
      </div> -->
      <div class="inner-profile-manu">
          <h3>{{request.user.username|capfirst}}</h3>
         <div class="spans"><span><strong>Posts</strong><small>({{post_u}})</small></span> <span><strong>Followers</strong><small>({{request.user.followed_by.count}})</small></span></div> 
          <a href="{% url 'profilies:followers' %}">My Followers/Following</a>
      </div>
    </div>
    <div class="c_form">
        <form class="create-form" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
      
            <button type="submit">Post</button>
      
          </form>
      </div>
</div> 
  <section class="front">
    <div class="inner-front">
      
      <div class="post">
        {% for post in post%}
        <div class="inner-post">
          <div class="profile-img"><img src="{{post.author.profile.profile_img.url}}">
            <a href="{% url 'profilies:profile' post.author.username %}">{{post.author.username}} </a> <span> |   {{post.creat_at|timesince}} ago</span>
            
          </div>
          {% if post.author == request.user %}
          <div class="icone_post"><i class="fas fa-ellipsis-v"></i> 
          </div>
          
          <div class="post_menu">
            <ul>
              <li  id="border"><a href="{% url 'post_app:update' post.pk %}">Edit Post</a></li>
              <li><a href="{% url 'post_app:delete' post.pk %}">Delete Post</a></li>

            </ul>
          </div>
          {% endif %}
          <p>{{post.content}}</p>
          {% if post.img %}<div class="post-img"><img src="{{post.img.url}}"></div>{% endif %}
          
          <a href="{% url 'post_app:details' post.pk %}" id="link2">View Post</a>
        </div>
        {% endfor %}
      </div>
      <!-- <div class="latest_post"></div> -->
    </div>
  




  </section>
{% endblock %}

post/templates/post_app/like_section.html
    <p>{{total_likes}} Like{{ total_likes|pluralize }}</p>  
   <form method="post" action="{% url 'post_app:post-like' %}">
        {% csrf_token%}
        {% if is_like %}
          <button type="submit" name="post_id" value="{{ post.id }}" id="btn1" class="liked">Liked!</button>
          {% else %}
          <button type="submit" name="post_id" value="{{ post.id }}" id="btn1" class="notliked">Like</button>
        {% endif %}
       </form>
  

post/templates/post_app/main.html
{% extends 'base.html' %}
{% block content %}
    <section class="front-page">
        <div class="col1">
            <div class="inner-1">
            <span><i class="fas fa-search"></i></span><span class="text">Follow your interests.</span><br><br><br>
            <span><i class="fas fa-user-friends"></i></span><span class="text">Hear what people are talking about.</span><br><br><br>
            <span><i class="fas fa-smile-wink"></i></span><span class="text">Have An Awasome Day.</span><br>
  
  
            </div>
  
  
        </div>
        <div class="col2">
            <div class="inner-2">
            <h2>See What Happining In The World Right Now!</h2><br>
            {% if user.is_authenticated %}
            <button style="background: #1d44f2"><a href="{% url 'post_app:index' %}">News Feed</a></button><br>
            <button style="background: none;border: 2px solid #1d44f2"><a href="{% url 'post_app:allposts' %}" style="color: #1d44f2">All Post</a></button>
            {% else %}
            <button style="background: #1d44f2"><a href="{% url 'accounts:signup' %}">Sign Up</a></button><br>
            <button style="background: none;border: 2px solid #1d44f2"><a href="{% url 'accounts:login' %}" style="color: #1d44f2">Log In</a></button>
            {% endif %}
            </div>
        </div>
        
    </section>
{% endblock %}

post/templates/post_app/update.html
 {% extends 'base.html' %} 
 {% block content %}
 <div class="update-form">
  <form method="post" class="u-form">
      {% csrf_token%}
      {{form.as_p}}
      <button type="submit" name="button">Update</button>

    </form>
  </div>   
  {% endblock %} 