accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.contrib.auth import views as auth_views

app_name="accounts"


urlpatterns = [
    
    path('signup/',views.signup,name='signup'),
    path('account-settings/',views.account_settings,name='account-setting'),
    path('password/',views.passchange,name='passchange'),
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name="login"),
    path('logout/',auth_views.LogoutView.as_view(template_name='accounts/login.html'),name="logout"),

]

instagram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls',namespace="post_app")),
    path('profile/',include('profiles.urls',namespace="profiles")),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('oauth/', include('social_django.urls', namespace='social')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views


app_name="post_app"


urlpatterns = [
    path('newsfeed/',views.index,name="index"),
    path('',views.main,name="main"),


    # path('post/<int:pk>',views.index,name="index"),


    path('edit/<int:pk>',views.update,name="update"),
    path('delete/<int:pk>',views.delete,name="delete"),
    path('<int:pk>/',views.details,name="details"),
    path('like/',views.like,name="post-like"),
    path('posts/',views.all_post,name="allposts"),


    

]

profiles/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views


app_name="profilies"


urlpatterns = [  
    # path('profile/',views.profile,name="profile-form"),
    path('profile-edit/',views.profile_update,name="profile-update"),
    path('<str:username>/follow/',views.Userfollow,name="follow"),
    path('',views.search,name="search"),
    path('<str:author>/',views.profile,name="profile"),
    path('<str:author>/photos',views.profile_p,name="photos"),
    path('<str:author>/about',views.profile_a,name="about"),
    path('user/followers/',views.follow_list,name="followers"),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
	<link href="https://fonts.googleapis.com/css?family=Dancing+Script:700" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
	<link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/file.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	


	<title></title>
	
</head>
<body>
	{% if main == false %}
	{% if user.is_authenticated %}
	<header class="m-header">
        <nav>
            <div class="logo"><h3>Insta Pic</h3></div>
            <div class="search-bar">
                <form action="{% url 'profilies:search' %}" method="get">
                    <input type="search" name="q"><button type="submit"><i class="fas fa-search"></i></button> 
                </form>
            </div>
            <div class="list">
                <ul>
                    <li><a href="{% url 'post_app:index' %}">News Feed</a></li>
                    <li><a href="{% url 'post_app:allposts' %}">All Posts</a></li>
                </ul>
            </div>
            <div class="name"><p>Hi <a href="{% url 'profilies:profile' request.user.username %}">{{request.user.username|capfirst}}</a> <span><i class="fas fa-user-alt"></i></span>
                <ul>
                    <li><a href="{% url 'accounts:account-setting' %}">Accounts Settings</a></li>
                    <li><a href="{% url 'profiles:profile-update' %}">Profile Settings</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>

                </ul>
            
            </p></div>
        </nav>
    </header>
	<header class="r-header">
			<nav>
				<div class="r-logo"><p>Insta pic</p></div>
				<div class="r-bar">
					<form action="" method="get">
						<input type="search" value=""><button type="submit"><i class="fas fa-search"></i></button>
					</form>
				</div>
				<div class="r-menue">
					<i class="fas fa-bars"></i>
				</div>
			</nav>
		</header>
		<div class="r-nbar">
			<ul>
				<li><a href="{% url 'profilies:profile' request.user.username %}"><h3>Hi Asad</h3></a></li>
				<li><a href="{% url 'post_app:index' %}"><h3>News Feed</h3></a></li>
                <li><a href="{% url 'post_app:allposts' %}"><h3>All Posts</h3></a></li>
				<li><a href="{% url 'accounts:account-setting' %}"><h3>Account Settings</h3></a></li>
				<li><a href="{% url 'profiles:profile-update' %}"><h3>Profile Settings</h3></a></li>
				<li><a href="{% url 'accounts:logout' %}"><h3>Log Out</h3></a></li>
			</ul>
		</div>
	{% else %}
	<header class="nah">
		
		<nav>
			
			<div class="logo"><p>Insta Pic</p></div>
			
			<div class="ls-btn">
				<button id="btn5"><a href="{% url 'accounts:login' %}" >Login</a></button>
				<button id="btn6"><a href="{% url 'accounts:signup' %}">SignUp</a></button>

			</div>
		</nav>

	</header>
	{% endif %}
	{% endif %}
	<div class="notification">
		{% if messages %}
			{% for message in messages %}
			  <div class="inner-notification">
				{{ message }}
			  </div>
			{% endfor %}
		{% endif %}
	</div>
{% block content %}
{% endblock %}


	<script type="text/javascript">
		$(document).ready(function(){
			$(".icone_post").click(function(){
				$(this).next().toggleClass('active')
			})
		})
		$(".reply-s form").addClass('replyyyy');

		$(document).ready(function(){
			$(".name i").click(function(){
				$('.name ul').toggle()
			})
		})
		$(document).ready(function(){
			$(".r-menue i").click(function(){
				$('.r-nbar').slideToggle(200)
			})
		})
		$(document).ready(function(){
			$("#style2").click(function(){
			$('.reply-s').toggle()
				})
		})
		$(document).ready(function(e){
			$(document).on('click','#btn1',function(e){
				e.preventDefault()
				var pk=$(this).attr('value');
				$.ajax({
					type:"POST",
					url:'{% url "post_app:post-like" %}',
					data:{'id': pk, 'csrfmiddlewaretoken': '{{csrf_token}}'},
					dataType:'json',
					success:function(response){
						$('#like').html(response['form'])
					},
					error:function(rs,e){
						console.log(rs.responseText);
					},
				})
			})
		})



		$(document).on('submit','.comment-formm',function(e){
			e.preventDefault()
			$.ajax({
				type:"POST",
				url:$(this).attr('action'),
				data:$(this).serialize(),
				dataType:'json',
				success:function(response){
					$('#main-comment-section').html(response['form']);
					$('.comment-form').val('');

				},
				error:function(rs,e){
					console.log(rs.responseText)
				}
			})
		})

		$(document).on('submit','.reply-formm',function(e){
			e.preventDefault()
			$.ajax({
				type:"POST",
				url:$(this).attr('action'),
				data:$(this).serialize(),
				dataType:'json',
				success:function(response){
					$('#main-comment-section').html(response['form']);
					$('.comment-form').val('')
				},
				error:function(rs,e){
					console.log(rs.responseText)
				}
			})
		})
	</script>
</body>
</html>

templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        *{margin: 0;
        padding: 0;}
        .r-header{
            height: 50px;
            line-height: 50px;
            box-shadow: 0 0 10px 1px black;
        }
        nav{
            display: grid;
            grid-template-columns: 1fr 2fr 1fr;
        }
        .r-logo p{
            float: right;
            padding-right: 30px;
        }
        .r-bar form{
            width: 100%;
        }
        .r-bar input{
            width: 90%;
        }
        .r-menue a{
            float: right;
            padding-right: 30px;
        }
        .r-nbar{
            width: 100%;
            height: 90vh;
            display: none;
        }
        .r-nbar ul{
            width: 100%;
            text-align: center;
            list-style: none;
        }
        .r-nbar ul a{
            color: blueviolet;
            text-decoration: none;
            display: block;
            height: 50px;
            line-height: 50px;
            border-bottom: 1px solid blueviolet;
        }
        
         

    
    </style>
</head>
<body>
    
</body>
</html>